version: '3'

services:
  web:
    build:
      context: .
      dockerfile: /Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/dromo
      - FLASK_ENV=development
    volumes:
      - ./app:/app/app
      - ./run.py:/app/run.py
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - ./outputs:/app/outputs
    command: gunicorn --bind 0.0.0.0:5000 run:app

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  test:
    build:
      context: .
      dockerfile: /Dockerfile
    volumes:
      - .:/app
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - MONGODB_URI=mongodb://mongo:27017/dromo_test
      - FLASK_ENV=testing
    # command: pytest

volumes:
  mongodb_data: